### ISSUE TITLE
Docker: Sample install of waltz as a docker image

### ISSUE THREAD

**Issue by kamransaleem** [finos/waltz#4802] opened 2020-04-06 08:56 UTC
Including sample data.

Ideal for someone who wants to see what Waltz can do.

**Comment by albertleigh** [comment] 2020-06-04 08:42
It would be so great to provide a demo purpose docker/docker-compose file to see what waltz can do and leverage these tons of unpleasant prerequisites which are just for environ setup…… it is a nightmare to setup things like this nowadays and devs definitely won’t like it……

**Comment by rovats** [comment] 2020-06-04 08:49
@albertleigh I have been working on this and there is a separate repo which has instructions on how to get Waltz up and running without installing any dependencies:

https://github.com/rovats/waltz-docker

There are instructions to spin up  a Postgres instance with sample data too. 
Please take a look if this helps. Any feedback will be welcome.

Eventually this separate repo will be merged with the main repo, once it has been battle tested.

**Comment by albertleigh** [comment] 2020-06-05 03:13
Thank @rovats for pointing out the docker helper repository; after checking the readme, it looks good to me and I would definitely give it a try shortly and provide the feedback.
Honestly speaking, I did not know much about waltz and it’s also why I wanna a try. 
But I have a feeling that, in the future, it might be ideal to provide an already built image instead of building on our own. 
I understand waltz might allow devs to deeply customize at codes level, but those could also be done via external configs from a volume mapping in docker-compse or pv/pvc in k8s. 

A typical example I could come up with is gitlab
https://docs.gitlab.com/omnibus/docker/
maybe it’s design could help explain better

External config might not merely up to few docker/config files, the whole project might need a refractor to reach there, which I donnot know whether that’s true for waltz.  But anyway, hope it could aid making some noise somehow and help you some kind. 

Take it easy and stay safe ~

**Comment by rovats** [comment] 2020-06-05 03:47
Thanks for your suggestions @albertleigh  
Yep, it shouldn't be too hard to provide a pre-built docker image/docker compose for demos now that we have docker files to build/run Waltz.

The current docker helper repo should take away a lot of the pain, but we will continue to work on this to improve user experience and make it simpler to install/upgrade Waltz, based on user feedback.

**Comment by mcleo-d** [comment] 2020-06-25 14:46
@davidwatkins73 and @rovats - I've just stumbled upon the [waltz-docker](https://github.com/rovats/waltz-docker) project whilst reviewing this issue. It's awesome @rovats 👍 

Have you considered contributing the project to FINOS so it sits alongside Waltz in the [FINOS Organisation](https://github.com/finos)? 🤔 😀

**Comment by rovats** [comment] 2020-06-25 15:50
Thanks @mcleo-d :)

I'd be very happy to contribute [waltz-docker](https://github.com/rovats/waltz-docker) to FINOS, please let me know how to proceed.

**Comment by davidwatkins73** [comment] 2020-06-25 21:57
In order to teach myself a little about docker and the associated eco-system I've created a simple docker-compose script and some sample pre-built images on dockerhub.  This sets up a postgres instance with sample data and a waltz (uberjar) instance connected to it.

There's a [screencast](https://waltz.finos.org/blog/waltz/admin/screencast/2020/06/25/run-docker-demo.html)  accessible via the Waltz blog.  The demo is running under Linux but I've checked also checked it on Windows 10.

It's important to note this is *not* a duplicate of @rovats work.  He is looking at a much more flexible and powerful way of building and managing Waltz.  This is just a very simple way to get people up and running with a demo instance.

**Comment by rovats** [comment] 2020-06-26 05:28
Nice one @davidwatkins73 , I've also raised an [issue](https://github.com/rovats/waltz-docker/issues/17) on waltz-docker to support installing/upgrading Waltz using pre-built release binaries, to provide another option to end users, apart from building from source.

**Comment by mcleo-d** [comment] 2020-06-26 10:57
@davidwatkins73 and @rovats - Both your comments above are amazing for engaging the developer community and I'd like to find a way to make them accessible to everyone who'd like to engage with Waltz. You're a super lean team! 🚀 🚀 🚀  

@rovats, regarding your comment ...
> I'd be very happy to contribute waltz-docker to FINOS, please let me know how to proceed.

Maybe we can jump on a call with @davidwatkins73 to discuss how Waltz, and all supporting materials, can sit within the FINOS organisation as a happy family? This could also mean bringing waltz-docker into the Waltz project team so it's supported from multiple angles.

Let me know your thoughts and I'll get a call set up for when's good for everyone 👏 👏 👏 

James

**Comment by rovats** [comment] 2020-06-26 11:38
Sounds good @mcleo-d , it would make sense to bring waltz-docker into the current Waltz project team, happy to discuss further.  

I am free next week:
* **Wed/Thu**: 10AM to 3PM UK time
* **Fri**: 12PM to 3PM UK time

**Closed** 2022-01-02 20:21 UTC
Labels: noteworthy
