### ISSUE TITLE
Bulk Assessment Editor: input broken for entity kinds that are not applications

### ISSUE THREAD

**Issue by jessica-woodland-scott-db** [finos/waltz#6627] opened 2023-05-24 07:51 UTC
### Description

The input box is hidden for licences and legal entity rel assessments

### Steps to Reproduce

1.
2.
3.
...

### Expected Result

Should be able to bulk upload for entity kinds other than apps

### Actual Result

No box for inputting data

**Comment by davidwatkins73** [comment] 2024-10-17 10:03
Dupe of #7156

**Closed by davidwatkins73** 2024-10-17 10:03 UTC
Labels: bug
